// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo807EDSeD0fmx2R0ncLMHqiQgKIS7Um4',
    appId: '1:174448020381:web:33bcef4ebe21a965447d74',
    messagingSenderId: '174448020381',
    projectId: 'doctor-channeling-app',
    authDomain: 'doctor-channeling-app.firebaseapp.com',
    databaseURL: 'https://doctor-channeling-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-channeling-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH33sA0isUnfAUng20qbAwZkg2NHrFL70',
    appId: '1:174448020381:android:592367dea0e3250a447d74',
    messagingSenderId: '174448020381',
    projectId: 'doctor-channeling-app',
    databaseURL: 'https://doctor-channeling-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-channeling-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc9TpQqabjCercApSCblvSV0rhXpTD1qg',
    appId: '1:174448020381:ios:e0d7e72168ef9228447d74',
    messagingSenderId: '174448020381',
    projectId: 'doctor-channeling-app',
    databaseURL: 'https://doctor-channeling-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-channeling-app.firebasestorage.app',
    iosBundleId: 'com.example.doctorChannelingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc9TpQqabjCercApSCblvSV0rhXpTD1qg',
    appId: '1:174448020381:ios:e0d7e72168ef9228447d74',
    messagingSenderId: '174448020381',
    projectId: 'doctor-channeling-app',
    databaseURL: 'https://doctor-channeling-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-channeling-app.firebasestorage.app',
    iosBundleId: 'com.example.doctorChannelingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo807EDSeD0fmx2R0ncLMHqiQgKIS7Um4',
    appId: '1:174448020381:web:4a1abad8c798fcc2447d74',
    messagingSenderId: '174448020381',
    projectId: 'doctor-channeling-app',
    authDomain: 'doctor-channeling-app.firebaseapp.com',
    databaseURL: 'https://doctor-channeling-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-channeling-app.firebasestorage.app',
  );
}
